/**
 * Advanced Post-Processing Pipeline for PaddleOCR PP-OCRv5 & Gemini Vision Results
 * Includes modular filters:
 * 1. [WatermarkFilter] & [GeometryFilter]: Bounding box outlier filter & watermark pattern matcher
 * 2. [HardFilter]: Drops pure noise (timestamps, resolution tags, isolated non-word symbols)
 * 3. [SoftFilter]: Normalizes text, trims stray bullet points, cleans control characters
 * 4. [LatinFilter]: Cleans garbled CJK or unknown glyph fragments when target language is Latin/Vietnamese/English
 * 5. [SingleCjkFilter]: Filters out single isolated CJK character false positives generated by background textures
 * 6. [BoundaryRefiner]: Refines start/end timestamps, snaps frame boundaries, and prevents timing drift
 * 7. [Merge] / [FillSkip]: Contiguous item merging & small timeline gap filling
 * 8. [Dedup]: High-level semantic deduplication via Gemini API
 */

import { LocalOcrResult } from './localPaddleOcrEngine';

export interface RawOcrItem {
  text: string;
  timestamp: number;
  confidence?: number;
  box?: number[]; // [ymin, xmin, ymax, xmax] 0-1000 or normalized
}

/**
 * 1. [GeometryFilter] & [WatermarkFilter]
 * Drops bounding boxes that are vertically absurd (too tall / vertical banners) or horizontally on far extreme edges (logos, watermarks)
 */
export function filterOutliersByGeometry<T extends { box?: number[]; text: string }>(
  items: T[],
  videoWidth: number = 1000,
  videoHeight: number = 1000
): T[] {
  if (!items || items.length === 0) return [];

  return items.filter((item) => {
    // Check watermark text first
    if (!applyWatermarkFilter(item.text, item.box)) return false;

    if (!item.box || item.box.length < 4) return true; // Keep if no box info

    const [ymin, xmin, ymax, xmax] = item.box;
    const boxH = ymax - ymin;
    const boxW = xmax - xmin;

    // Normalize coordinates to 0-1000 scale if not already
    const normH = boxH > 1 ? (boxH / videoHeight) * 1000 : boxH * 1000;
    const normW = boxW > 1 ? (boxW / videoWidth) * 1000 : boxW * 1000;
    const normYmin = ymin > 1 ? (ymin / videoHeight) * 1000 : ymin * 1000;
    const normXmin = xmin > 1 ? (xmin / videoWidth) * 1000 : xmin * 1000;

    // Filter-Height: Drop boxes that take > 450/1000 (45%) of screen height (vertical ads/banners) or < 6/1000 (too small)
    if (normH > 450 || normH < 6) return false;

    // Filter-Horizontal: Drop boxes that sit exclusively in extreme top corner (< 5% width margin) and top height (watermark zone)
    if (normYmin < 80 && (normXmin < 40 || normXmin + normW > 960)) {
      if (normW < 220 && normH < 120) return false;
    }

    return true;
  });
}

/**
 * Dedicated [WatermarkFilter]
 * Filters out common watermarks, logo signatures, channel credits, and social handles
 */
export function applyWatermarkFilter(text: string, box?: number[]): boolean {
  if (!text) return false;
  const trimmed = text.trim();

  // Common watermark keywords & social handles
  const watermarkPatterns = [
    /^(capcut|tiktok|douyin|kwai|youtube|facebook|instagram)\b/i,
    /@[\w_]{3,}/i, // Social handle e.g. @user123
    /^(subscribe|like\s*&\s*share|theo\s*dõi|đăng\s*ký\s*kênh|bản\s*quyền\s*thuộc\s*về|video\s*by)\b/i,
    /^(wm|watermark|id:\s*\d+|uid:\s*\d+)$/i,
  ];

  for (const pattern of watermarkPatterns) {
    if (pattern.test(trimmed)) return false;
  }

  return true;
}

/**
 * 2. [HardFilter]
 * HardFilter handles structural noise independently without deleting valid short sentences.
 * Drops pure punctuation, video player seek timestamps, resolution badges, or unreadable confidence noise.
 * When isCjkExpected is true, drops isolated Latin/digit fragments without meaningful CJK ideographs (e.g. "2 7", "1 X", "12VG", "0C", "A Z", "2").
 */
export function applyHardFilter(
  text: string,
  confidence: number = 1.0,
  minConfidence: number = 0.60,
  isCjkExpected: boolean = false
): boolean {
  if (!text) return false;
  const trimmed = text.trim();

  // Reject low confidence OCR noise
  if (confidence < minConfidence) return false;

  // Drop if empty
  if (trimmed.length === 0) return false;

  // Drop if text contains ONLY punctuation, symbols, or pure whitespace
  if (/^[\p{P}\p{S}\s]+$/u.test(trimmed)) {
    return false;
  }

  // Drop if it's just pure numbers or isolated math symbols without letters (e.g. "...", "---", "###", "12345678", "2 7", "00 9")
  if (/^[.\-!?,:;~_+=*/\\|@#$%^&*()\[\]{}<>"'\s\d]+$/.test(trimmed) && !/[\p{L}]/u.test(trimmed)) {
    return false;
  }

  // Drop pure numeric string longer than 5 digits (timestamp/ID) or pure digits/spaces like "2 7", "2", "00 9"
  if (/^[\d\s]+$/.test(trimmed)) {
    return false;
  }

  // HardFilter: Drop video player seek controls & resolution badges
  if (/^\d{1,2}:\d{2}\s*[/|-]\s*\d{1,2}:\d{2}$/.test(trimmed)) return false;
  if (/^(1080p|720p|4k|60fps|hd|sub|cc|subscribe|like|share)$/i.test(trimmed)) return false;

  // When CJK is expected: drop pure short noise like "1 X", "12VG", "0C", "A Z", "fiM", "SRr", "C", "E", "ee", "gia", "(D)" that contain NO CJK characters at all
  if (isCjkExpected) {
    const hasCjk = /[\u4e00-\u9fff\u3400-\u4dbf]/.test(trimmed);
    if (!hasCjk) {
      // Whitelist valid standalone English acronyms/short words that can legitimately appear in CJK subtitles
      const cleanWord = trimmed.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
      const allowedAbbr = new Set([
        'OK', 'VIP', 'DNA', 'CPU', 'GPU', 'FBI', 'CEO', 'APP', 'KTV', 'NPC', 'SOS',
        'AI', 'BYE', 'HI', 'YES', 'NO', 'CD', 'DVD', 'TV', 'ID', 'HD', '3D', '4D',
        'VR', 'AR', 'WIFI', 'GPS', 'SIM', 'SMS', 'ATM', 'POS', 'PPT', 'PDF', 'MV',
        'PK', 'CP', 'CCTV', 'NBA', 'CBA', 'KFC', 'DJ', 'MC', 'UFO', 'MVP'
      ]);

      // If not in allowed whitelist, drop any non-CJK string when CJK is expected
      if (!allowedAbbr.has(cleanWord)) {
        return false;
      }
    }
  }

  return true;
}

/**
 * Helper to determine if a language code or name represents Latin/Vietnamese/English
 */
export function isLatinLanguage(lang?: string): boolean {
  if (!lang) return false;
  const l = lang.toLowerCase().trim();
  return (
    l.startsWith('vi') ||
    l.startsWith('en') ||
    l.startsWith('fr') ||
    l.startsWith('es') ||
    l.startsWith('de') ||
    l.startsWith('id') ||
    l.startsWith('pt') ||
    l.startsWith('it') ||
    l.startsWith('ru') ||
    l.includes('tiếng việt') ||
    l.includes('vietnamese') ||
    l.includes('english')
  );
}

/**
 * Strip stray embedded Latin/digits noise tokens from CJK subtitle text.
 * When text contains CJK ideographs, OCR often picks up edge noise fragments
 * such as "Y 4 67 fiM SRr 咱们惹不起啊", "A 咱们惹不起啊 RASas ciM", "你安排一半人9 V 心", "保密 00 9".
 * This function strips those isolated Latin/number tokens while preserving the core sentence.
 * If text contains NO CJK characters and is not an allowed English abbreviation, it returns empty string "".
 */
export function stripEmbeddedNoiseTokens(text: string): string {
  if (!text) return '';
  const trimmed = text.trim();
  const hasCjk = /[\u4e00-\u9fff\u3400-\u4dbf]/.test(trimmed);
  if (!hasCjk) {
    const cleanWord = trimmed.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
    const allowedAbbr = new Set([
      'OK', 'VIP', 'DNA', 'CPU', 'GPU', 'FBI', 'CEO', 'APP', 'KTV', 'NPC', 'SOS',
      'AI', 'BYE', 'HI', 'YES', 'NO', 'CD', 'DVD', 'TV', 'ID', 'HD', '3D', '4D',
      'VR', 'AR', 'WIFI', 'GPS', 'SIM', 'SMS', 'ATM', 'POS', 'PPT', 'PDF', 'MV',
      'PK', 'CP', 'CCTV', 'NBA', 'CBA', 'KFC', 'DJ', 'MC', 'UFO', 'MVP'
    ]);
    if (!allowedAbbr.has(cleanWord)) {
      return '';
    }
    return trimmed;
  }

  let cleaned = trimmed;

  // 1. Remove isolated Latin words / tokens (1 to 5 characters, e.g. "Y", "fiM", "SRr", "RASas", "ciM", "V", "E", "AZ", "gia", "ee")
  cleaned = cleaned.replace(/(?<![\p{L}\p{N}])[A-Za-z]{1,5}(?![\p{L}\p{N}])/gu, ' ');

  // 2. Remove isolated numbers / digits (e.g. "4", "67", "9", "00", "0", "1", "2") that are detached or adjacent to CJK
  cleaned = cleaned.replace(/(?<![\p{L}\p{N}])\d{1,4}(?![\p{L}\p{N}])/gu, ' ');

  // 3. Clean leading / trailing non-CJK noise tokens before / after CJK text blocks
  cleaned = cleaned.replace(/^[A-Za-z0-9\s\p{P}]+(?=[\u4e00-\u9fff\u3400-\u4dbf])/u, '');
  cleaned = cleaned.replace(/(?<=[\u4e00-\u9fff\u3400-\u4dbf])[A-Za-z0-9\s\p{P}]+$/u, '');

  // 4. Strip extra whitespace and join CJK words
  cleaned = cleaned.replace(/\s+/g, ' ').trim();
  // Join spaces between CJK characters
  cleaned = cleaned.replace(/([\u4e00-\u9fa5\u3400-\u4dbf\u3040-\u30ff\uac00-\ud7af])\s+([\u4e00-\u9fa5\u3400-\u4dbf\u3040-\u30ff\uac00-\ud7af])/g, '$1$2');

  return stripOcrArtifactCharacters(cleaned);
}

/**
 * 3. [SoftFilter]
 * SoftFilter normalizes text, trims stray bullet points, cleans control characters, and fixes spacing
 */
export function applySoftFilter(text: string): string {
  if (!text) return '';
  let cleaned = text.replace(/[\x00-\x1F\x7F]/g, '').trim();

  // Strip leading/trailing stray bullet points, dashes, or orphan symbols
  cleaned = cleaned.replace(/^[•\-–—*#+]+\s*/, '');
  cleaned = cleaned.replace(/\s*[•*#+]+$/, '');

  // Normalize multiple spaces
  cleaned = cleaned.replace(/\s+/g, ' ').trim();
  return cleaned;
}

/**
 * 4. [LatinFilter]
 * Handles wrong-script contamination independently.
 * Removes garbled non-Latin or stray CJK glyph fragments when the target language is Latin/Vietnamese/English.
 */
export function applyLatinFilter(text: string, isLatinExpected: boolean = true): string {
  if (!text) return '';
  if (!isLatinExpected) return text;

  // Strip isolated CJK range or full-width symbol fragments
  let result = text.replace(/[\u3000-\u303f\u3040-\u309f\u30a0-\u30ff\uff00-\uffef]/g, ' ');
  result = result.replace(/\s+/g, ' ').trim();
  return result;
}

/**
 * 5. [SingleCjkFilter]
 * Specifically isolates single CJK character noise generated by background video textures in non-CJK videos.
 */
export function applySingleCjkFilter(text: string, isCjkExpected: boolean = false): boolean {
  if (!text) return false;
  if (isCjkExpected) return true; // Keep CJK if video is CJK

  const trimmed = text.trim();

  // Check if string length is 1 and character is CJK
  if (trimmed.length === 1) {
    const code = trimmed.charCodeAt(0);
    // CJK Unified Ideographs block
    if (code >= 0x4e00 && code <= 0x9fff) {
      return false; // Drop single CJK character
    }
  }

  return true;
}

/**
 * Strips ghost/phantom single-stroke Chinese characters, stray radicals, floating modal particles,
 * and CTC bounding-box boundary noise artifacts at the very start (head) or end (tail) of subtitle text.
 * E.g.:
 * - "丶咱们惹不起啊" -> "咱们惹不起啊"
 * - "丨这就去办" -> "这就去办"
 * - "好既如此一" -> "好既如此"
 * - "孙老爷急着去哪啊一" -> "孙老爷急着去哪啊"
 * - "你安排一半人口" -> "你安排一半人"
 * - "一这是什么东西" -> "这是什么东西"
 * - "口就能找出幕后之人" -> "就能找出幕后之人"
 * - "啊怎么会这样" -> "怎么会这样"
 * - "还说结案后一丶" -> "还说结案后"
 */
export function stripEdgeNoiseHanziTokens(text: string): string {
  if (!text) return '';
  let s = text.trim();

  const hasCjk = /[\u4e00-\u9fff\u3400-\u4dbf]/.test(s);
  if (!hasCjk) return s;

  // Whitelist of valid Chinese multi-character words / compounds starting with "口"
  const validLeadingKou = /^(口碑|口袋|口角|口才|口语|口粮|口气|口令|口供|口头|口齿|口音|口味|口红|口信|口实|口决|口诀|口渴|口吻|口号|口服|口罩|口试|口吃|口拙|口诛|口木|口算|口译|口腔|口述|口条|口疮|口风|口紧|口轻)/;

  // Whitelist of valid words starting with "了", "着", "过"
  const validLeadingParticles = /^(了解|了结|了不起|了然|了如指掌|着重|着想|着手|着陆|着急|着力|着落|着眼|着迷|着实|过去|过分|过度|过错|过瘾|过往|过关|过目|过程|过滤|过问|过节|过夜|过头|过招|过秤|过客)/;

  // Whitelist of valid Chinese words/compounds ending in "一"
  const validTrailingYi = /(?:第一|周一|星期一|礼拜一|初一|高一|大一|专一|唯一|合二为一|始终如一|万分之一|百分之一|归一|万一|统一|不一|九九归一|天人合一|表里如一|政企合一|二合一|三合一|缺一|加一|数一数二|独一无二)$/;

  // Whitelist of valid Chinese words/compounds ending in "口"
  const validTrailingKou = /(?:伤|借|关|胸|门|入|出|路|渡|港|窗|虎|胃|海|风|枪|水|井|破|糊|松|亲|张|合|开|闭|随|灭|改|夸|漱|忌|吞|咽|交|众|人|户|大|小|两|三|四|五|多|这|那|一|脱|换|封|转|缺)口$/;

  // Iterative pass to strip combined edge noise (e.g. "丶一你好" or "你好。一丶")
  let changed = true;
  let iterations = 0;
  while (changed && iterations < 5) {
    changed = false;
    iterations++;

    // 1. Strip leading & trailing symbols, bullets, dashes, brackets, colons, punctuation
    const beforeSymbols = s;
    s = s.replace(/^[—–\-·•·■□▲◆\s.,;:!?~_+=*/\\|@#$%^&*()\[\]{}<>"'“”‘’（）【】《》、，。！？：；…]+/, '');
    s = s.replace(/[—–\-·•·■□▲◆\s.,;:!?~_+=*/\\|@#$%^&*()\[\]{}<>"'“”‘’（）【】《》、，。！？：；…]+$/, '');
    if (s !== beforeSymbols) changed = true;

    if (s.length < 2) break;

    // 2. Strip leading single-stroke radicals / noise characters: 丶, 丨, 丿, 亅, 乙, 乚, 十, 卜, 丁, 厂, 冖, 冫, 几, 凵, 勹, 匕, 匚, 冂, 卩, 厶, 又
    const leadingRadicalPattern = /^[丶丨丿亅乙乚卜丁冖冫几凵勹匕匚冂卩厶又](?=[\u4e00-\u9fff\u3400-\u4dbf])/;
    if (leadingRadicalPattern.test(s) && s.length >= 2) {
      s = s.slice(1).trim();
      changed = true;
    }

    // 3. Strip leading spurious "一" before pronouns, verbs, modals, prepositions, adverbs, conjunctions
    if (s.startsWith('一') && s.length >= 2) {
      const leadingYiPattern = /^一(?=[这那你有我是他她它您谁甚什怎为因所快别请去到在听看想要能可真太没不若虽当好就但如果现原其然既已经将只被给把让再还正刚自从与跟及或该此处各每某即便乃莫非毋勿未否岂何胡曷奚安焉聊且姑略微稍渐极甚颇最更越愈益顶倒反却偏哪怕就算纵然即便只要除非以免大家大伙])/;
      if (leadingYiPattern.test(s)) {
        s = s.slice(1).trim();
        changed = true;
      }
    }

    // 4. Strip leading spurious "口" when not forming a valid "口*" word
    if (s.startsWith('口') && s.length >= 2 && !validLeadingKou.test(s)) {
      s = s.slice(1).trim();
      changed = true;
    }

    // 5. Strip leading modal/speech particles (sentence-final particles cannot grammatically begin a sentence)
    if (s.length >= 2 && /^[了吧呢吗啊呀哇么嘛啦喽]/.test(s) && !validLeadingParticles.test(s)) {
      s = s.slice(1).trim();
      changed = true;
    }

    // 6. Strip leading isolated "个", "的", "得", "地" before pronouns/verbs
    if (s.length >= 2 && /^[个的得地](?=[你我他她它您这那谁甚什怎快别请])/.test(s)) {
      s = s.slice(1).trim();
      changed = true;
    }

    if (s.length < 3) break;

    // 7. Strip trailing single-stroke radicals: 丶, 丨, 丿, 亅, 乙, 乚, 卜, 丁, 冖, 冫, 几, 凵, 勹, 匕, 匚, 冂, 卩, 厶, 又
    const trailingRadicalPattern = /[丶丨丿亅乙乚卜丁冖冫几凵勹匕匚冂卩厶又]$/;
    if (trailingRadicalPattern.test(s) && s.length >= 3) {
      s = s.slice(0, -1).trim();
      changed = true;
    }

    // 8. Strip trailing spurious "一" at the end of Chinese phrases (not in validTrailingYi)
    if (s.endsWith('一') && s.length >= 3 && !validTrailingYi.test(s)) {
      s = s.slice(0, -1).trim();
      changed = true;
    }

    // 9. Strip trailing spurious "口" at the end of Chinese phrases (not in validTrailingKou)
    if (s.endsWith('口') && s.length >= 3 && !validTrailingKou.test(s)) {
      s = s.slice(0, -1).trim();
      changed = true;
    }

    // 10. Strip trailing double-particle artifacts (e.g. "...啊个", "...呢个", "...吧个", "...吗个", "...啊了", "...呢了", "...吧了", "...吗了")
    const beforeDoubleParticle = s;
    s = s.replace(/([啊呢吧吗呀哇么嘛啦喽])([个了一口丶丨丿亅])$/, '$1');
    if (s !== beforeDoubleParticle) changed = true;
  }

  return s;
}

/**
 * Strips leading/trailing spurious characters (such as "一" or "口" or "—" / bullets)
 * that are OCR misreadings of subtitle dash lines "—" or frame bullet icons "■"/"□".
 */
export function stripOcrArtifactCharacters(text: string): string {
  if (!text) return '';
  let s = text.trim();

  const hasCjk = /[\u4e00-\u9fff\u3400-\u4dbf]/.test(s);
  if (!hasCjk) return s;

  return stripEdgeNoiseHanziTokens(s);
}

/**
 * [SafetyNet], [Anomaly], [Correct]
 * Normalizes text, fixes unclosed quotes/brackets, fixes double spaces, fixes CJK confused glyphs and common OCR letter swaps
 */
export function correctOcrTextAnomalies(text: string): string {
  if (!text) return '';
  let s = applySoftFilter(text);

  // 1. CJK Space Cleanup: Strip spaces between Chinese/Japanese/Korean characters inserted by OCR
  s = s.replace(/([\u4e00-\u9fa5\u3040-\u30ff\uac00-\ud7af])\s+([\u4e00-\u9fa5\u3040-\u30ff\uac00-\ud7af])/g, '$1$2');
  s = s.replace(/([\u4e00-\u9fa5\u3040-\u30ff\uac00-\ud7af])\s+([\u4e00-\u9fa5\u3040-\u30ff\uac00-\ud7af])/g, '$1$2');

  // 1b. CJK Common OCR Confusion Matrix Correction (Fixing visual glyph misrecognitions in Lightweight Tiny Models)
  // Fix 亥 / 玄 confusion (e.g., "陈亥" -> "陈玄", "陳亥" -> "陳玄")
  s = s.replace(/陈亥/g, '陈玄').replace(/陳亥/g, '陳玄');
  // Fix 蛻 / 蜕 normalization
  s = s.replace(/蛻/g, '蜕');
  // Fix 説 / 说 / 說
  s = s.replace(/説/g, '说');
  // Fix 什麽 / 什莫 / 爲什麽
  s = s.replace(/什麽/g, '什么').replace(/爲什麽/g, '为什么').replace(/什莫/g, '什么');
  // Fix 'O' / 'o' mistaken for digit '0' in CJK numeric contexts (e.g., "花5O两" -> "花50两", "5O" -> "50", "1O0" -> "100")
  s = s.replace(/(\d+)[Oo]([\u4e00-\u9fa5\u3400-\u4dbf\d])/g, '$10$2');
  s = s.replace(/([\u4e00-\u9fa5\u3400-\u4dbf])(\d*)[Oo](\d*)([\u4e00-\u9fa5\u3400-\u4dbf])/g, '$1$20$3$4');
  s = s.replace(/([\u4e00-\u9fa5\u3400-\u4dbf])[Oo]([\u4e00-\u9fa5\u3400-\u4dbf])/g, '$10$2');

  // 1c. Strip Leading/Trailing spurious "一" or "口" or dashes
  s = stripOcrArtifactCharacters(s);

  // 2. Correct OCR character swaps in Latin/Vietnamese word contexts
  s = s.replace(/\b([A-Za-z])1([A-Za-z])\b/g, '$1i$2');
  s = s.replace(/\b0([a-z]{2,})\b/g, 'o$1'); // "0ne" -> "one"
  s = s.replace(/\bvv([a-z]+)\b/gi, 'w$1'); // "vith" -> "with"

  // 3. Fix spaced Vietnamese tone accents e.g. "a '" -> "á"
  s = s.replace(/([a-zA-Z\u00C0-\u1EF9])\s+(['`?~.])/g, '$1$2');

  // 4. Fix unclosed quotes
  const doubleQuotes = (s.match(/"/g) || []).length;
  if (doubleQuotes % 2 !== 0) {
    if (s.startsWith('"') && !s.endsWith('"')) s = s + '"';
    else if (!s.startsWith('"') && s.endsWith('"')) s = '"' + s;
  }

  // 5. Fix unclosed brackets
  if (s.includes('(') && !s.includes(')')) s = s + ')';
  if (s.includes('[') && !s.includes(']')) s = s + ']';

  return s.trim();
}

/**
 * Levenshtein similarity score between two strings (0.0 to 1.0)
 */
export function getTextSimilarityScore(str1: string, str2: string): number {
  const s1 = (str1 || '').trim().toLowerCase();
  const s2 = (str2 || '').trim().toLowerCase();
  if (s1 === s2) return 1.0;
  if (!s1 || !s2) return 0.0;

  const len1 = s1.length;
  const len2 = s2.length;
  const maxLen = Math.max(len1, len2);
  if (maxLen === 0) return 1.0;

  const matrix: number[][] = [];
  for (let i = 0; i <= len1; i++) matrix[i] = [i];
  for (let j = 0; j <= len2; j++) matrix[0][j] = j;

  for (let i = 1; i <= len1; i++) {
    for (let j = 1; j <= len2; j++) {
      const cost = s1[i - 1] === s2[j - 1] ? 0 : 1;
      matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      );
    }
  }

  const distance = matrix[len1][len2];
  return 1.0 - distance / maxLen;
}

/**
 * Calculates character overlap ratio (Dice coefficient on character sets or n-grams)
 * Highly effective for CJK & text with minor OCR typos or partial word recognitions
 */
export function getCharacterOverlapRatio(str1: string, str2: string): number {
  const s1 = (str1 || '').trim().toLowerCase().replace(/\s+/g, '');
  const s2 = (str2 || '').trim().toLowerCase().replace(/\s+/g, '');
  if (!s1 || !s2) return 0;
  if (s1 === s2) return 1.0;

  // Substring inclusion check
  if (s1.includes(s2) || s2.includes(s1)) {
    const minLen = Math.min(s1.length, s2.length);
    const maxLen = Math.max(s1.length, s2.length);
    if (minLen / maxLen >= 0.3) return 0.90;
  }

  const set1 = new Map<string, number>();
  for (const char of s1) {
    set1.set(char, (set1.get(char) || 0) + 1);
  }

  let intersection = 0;
  const set2 = new Map<string, number>();
  for (const char of s2) {
    set2.set(char, (set2.get(char) || 0) + 1);
  }

  for (const [char, count1] of set1.entries()) {
    const count2 = set2.get(char) || 0;
    intersection += Math.min(count1, count2);
  }

  const totalLen = s1.length + s2.length;
  if (totalLen === 0) return 0;
  return (2.0 * intersection) / totalLen;
}

/**
 * Calculates a cleanliness score (0 to 100+) favoring clean CJK / language text with minimal embedded noise tokens
 */
export function getCleanlinessScore(text: string): number {
  if (!text) return 0;
  const trimmed = text.trim();
  if (trimmed.length === 0) return 0;

  const cjkMatches = trimmed.match(/[\u4e00-\u9fff\u3400-\u4dbf]/g) || [];
  const latinMatches = trimmed.match(/[A-Za-z]/g) || [];
  const digitMatches = trimmed.match(/\d/g) || [];
  const symbolMatches = trimmed.match(/[^\p{L}\p{N}\s]/gu) || [];

  // If text has CJK characters:
  if (cjkMatches.length > 0) {
    const cjkCount = cjkMatches.length;
    // Heavy penalty for random Latin and digit tokens in CJK subtitles
    const noiseCount = latinMatches.length * 1.5 + digitMatches.length * 1.2 + symbolMatches.length * 0.5;
    const ratio = cjkCount / (cjkCount + noiseCount);
    return ratio * 100 + cjkCount * 2;
  }

  // Non-CJK text (Vietnamese / English):
  const wordLetters = latinMatches.length;
  const noiseCount = digitMatches.length + symbolMatches.length;
  return (wordLetters / Math.max(1, wordLetters + noiseCount)) * 100;
}

/**
 * Determines whether two OCR text strings represent the same subtitle line
 * considering time gap, Levenshtein edit distance, character overlap, and edge noise removal.
 */
export function isSameSubtitleLine(text1: string, text2: string, timeGap: number): boolean {
  const raw1 = (text1 || '').trim().toLowerCase();
  const raw2 = (text2 || '').trim().toLowerCase();
  if (!raw1 || !raw2) return false;
  if (raw1 === raw2) return true;

  // Extract core text by stripping edge ghost tokens & embedded noise tokens
  const clean1 = stripEdgeNoiseHanziTokens(stripEmbeddedNoiseTokens(raw1)).trim().toLowerCase();
  const clean2 = stripEdgeNoiseHanziTokens(stripEmbeddedNoiseTokens(raw2)).trim().toLowerCase();

  // If both have cleaned core text and they are identical (e.g. "Y 4 67 fiM SRr 咱们惹不起啊一" vs "咱们惹不起啊"):
  if (clean1 && clean2 && clean1 === clean2) {
    return true;
  }

  const effective1 = clean1 || raw1;
  const effective2 = clean2 || raw2;

  if (effective1 === effective2) {
    return true;
  }

  const minLen = Math.min(effective1.length, effective2.length);
  const maxLen = Math.max(effective1.length, effective2.length);
  const lenRatio = maxLen > 0 ? minLen / maxLen : 0;

  // 1. Direct substring / inclusion check on core text
  const isSub1In2 = effective2.includes(effective1);
  const isSub2In1 = effective1.includes(effective2);
  const hasSubstringRelation = isSub1In2 || isSub2In1;

  // 2. Similarity metrics on core text
  const levSim = getTextSimilarityScore(effective1, effective2);
  const charOverlap = getCharacterOverlapRatio(effective1, effective2);
  const levDistance = Math.round((1 - levSim) * maxLen);

  // 3. Close temporal proximity check (timeGap <= 1.0s):
  // Catches initial/terminal character drops, CTC ghost edge mutations, and minor single-frame OCR variations
  if (timeGap <= 1.0) {
    // If one text is contained in the other with reasonable length ratio
    if (hasSubstringRelation && lenRatio >= 0.30) {
      return true;
    }

    // High character overlap or Levenshtein similarity (>= 65% similarity or >= 55% character overlap)
    if (charOverlap >= 0.55 || levSim >= 0.65) {
      return true;
    }

    // Small absolute edit distance (<= 2-3 character edits difference for short/medium phrases)
    const allowedEditDist = Math.max(2, Math.floor(maxLen * 0.35));
    if (levDistance <= allowedEditDist && lenRatio >= 0.40) {
      return true;
    }
  }

  // 4. Medium time gap (1.0s < timeGap <= 1.8s)
  if (timeGap <= 1.8) {
    if (hasSubstringRelation && lenRatio >= 0.45) return true;
    if (levSim >= 0.75 || charOverlap >= 0.68) return true;
    if (levDistance <= 2 && lenRatio >= 0.60) return true;
  }

  return false;
}

/**
 * Selects the best/longest, cleanest candidate text when merging OCR variations
 */
export function selectBestOcrText(text1: string, text2: string): string {
  const t1 = (text1 || '').trim();
  const t2 = (text2 || '').trim();
  if (!t1) return t2;
  if (!t2) return t1;
  if (t1 === t2) return t1;

  const clean1 = stripEmbeddedNoiseTokens(t1);
  const clean2 = stripEmbeddedNoiseTokens(t2);

  // Check CJK presence
  const hasCjk1 = /[\u4e00-\u9fff\u3400-\u4dbf]/.test(t1);
  const hasCjk2 = /[\u4e00-\u9fff\u3400-\u4dbf]/.test(t2);

  if (hasCjk1 || hasCjk2) {
    // If one has CJK and the other doesn't, always prefer the CJK one
    if (hasCjk1 && !hasCjk2) return clean1 || t1;
    if (!hasCjk1 && hasCjk2) return clean2 || t2;

    // Both have CJK: if core cleaned texts are identical or one contains the other
    if (clean1 === clean2) return clean1;
    if (clean1.includes(clean2) && clean2.length >= 2) return clean1;
    if (clean2.includes(clean1) && clean1.length >= 2) return clean2;

    // Compare cleanliness score (CJK ratio / least noise)
    const score1 = getCleanlinessScore(t1);
    const score2 = getCleanlinessScore(t2);
    if (Math.abs(score1 - score2) >= 5) {
      return score2 > score1 ? (clean2 || t2) : (clean1 || t1);
    }
    return (clean2.length > clean1.length ? clean2 : clean1) || t1;
  }

  const c1Lower = t1.toLowerCase();
  const c2Lower = t2.toLowerCase();
  if (c1Lower.includes(c2Lower)) return t1;
  if (c2Lower.includes(c1Lower)) return t2;

  const score1 = getCleanlinessScore(t1);
  const score2 = getCleanlinessScore(t2);
  return score2 > score1 ? t2 : t1;
}

/**
 * Finds the mode (most frequent or highest weighted item) in an array
 */
function getMode<T>(arr: T[]): T {
  const countMap = new Map<T, number>();
  let maxCount = 0;
  let modeVal = arr[0];
  for (const item of arr) {
    const cnt = (countMap.get(item) || 0) + 1;
    countMap.set(item, cnt);
    if (cnt > maxCount) {
      maxCount = cnt;
      modeVal = item;
    }
  }
  return modeVal;
}

/**
  Perform character-level majority voting across multiple OCR readings of the same line
  Corrects single-frame character recognition errors/typos
 */
export function majorityVote(readings: string[]): string {
  if (!readings || readings.length === 0) return '';
  const valid = readings.map((r) => (r || '').trim()).filter((r) => r.length > 0);
  if (valid.length === 0) return '';
  if (valid.length === 1) return valid[0];

  return pickBestReadingWithConfidence(valid.map(r => ({ text: r, confidence: 0.88 })));
}

/**
 * Selects the best candidate reading using OCR model confidence score + cleanliness score + character-level weighted voting
 * across frame samples to reconstruct the most accurate subtitle line.
 * Incorporates Technique 4: Language-Based Auto-Fill & Majority Voting (Character Sequence Alignment).
 */
export function pickBestReadingWithConfidence(readings: { text: string; confidence?: number }[]): string {
  if (!readings || readings.length === 0) return '';
  const valid = readings
    .map((r) => {
      const raw = (r.text || '').trim();
      const cleaned = stripEmbeddedNoiseTokens(correctOcrTextAnomalies(raw));
      const effective = cleaned || raw;
      return {
        text: effective,
        confidence: Math.max(0.1, r.confidence ?? 0.88),
        cleanliness: getCleanlinessScore(effective),
      };
    })
    .filter((r) => r.text.length > 0);

  if (valid.length === 0) return '';
  if (valid.length === 1) return valid[0].text;

  // Check if all texts are identical
  const firstText = valid[0].text;
  if (valid.every(v => v.text === firstText)) return firstText;

  // 1. Group readings by exact text and aggregate total confidence weights + cleanliness
  const textWeights = new Map<string, { totalWeight: number; count: number; avgConf: number; cleanliness: number }>();
  for (const item of valid) {
    const existing = textWeights.get(item.text) || { totalWeight: 0, count: 0, avgConf: 0, cleanliness: item.cleanliness };
    existing.totalWeight += item.confidence;
    existing.count += 1;
    existing.avgConf = existing.totalWeight / existing.count;
    if (item.cleanliness > existing.cleanliness) {
      existing.cleanliness = item.cleanliness;
    }
    textWeights.set(item.text, existing);
  }

  // Sort candidates by total confidence weight biased by cleanliness (favoring pure CJK over noisy mixed tokens)
  const sortedByWeight = Array.from(textWeights.entries()).sort((a, b) => {
    const scoreA = a[1].totalWeight * (1 + (a[1].cleanliness / 200));
    const scoreB = b[1].totalWeight * (1 + (b[1].cleanliness / 200));
    const diff = scoreB - scoreA;
    if (Math.abs(diff) < 0.20) {
      const cleanA = a[0].toLowerCase();
      const cleanB = b[0].toLowerCase();
      if (cleanA.includes(cleanB)) return -1;
      if (cleanB.includes(cleanA)) return 1;
      return b[0].length - a[0].length;
    }
    return diff;
  });
  const topTextGroup = sortedByWeight[0];

  // If top candidate appears in >= 40% of frame readings or has dominant weight, accept directly
  if (topTextGroup[1].count >= valid.length * 0.4 || sortedByWeight.length === 1) {
    return topTextGroup[0];
  }

  // Technique 4: Language-Based Majority Voting & Auto-Fill (Character Sequence Alignment)
  // Aligns candidate OCR readings across frames (e.g., Frame 1: 我想去中国, Frame 2: 我想 中国, Frame 3: 我想去中国)
  // using positional alignment and character frequency voting to automatically restore characters dropped in single frames.
  const sortedByLen = [...valid].sort((a, b) => b.text.length - a.text.length);
  const anchorText = sortedByLen[0].text;
  const resultChars: string[] = [];

  for (let i = 0; i < anchorText.length; i++) {
    const anchorChar = anchorText[i];
    const charVotes = new Map<string, number>();

    for (const r of valid) {
      if (r.text.length === anchorText.length) {
        const c = r.text[i];
        charVotes.set(c, (charVotes.get(c) || 0) + r.confidence);
      } else if (r.text.includes(anchorChar)) {
        charVotes.set(anchorChar, (charVotes.get(anchorChar) || 0) + r.confidence * 0.9);
      }
    }

    let topChar = anchorChar;
    let maxVote = charVotes.get(anchorChar) || 0;

    for (const [char, vote] of charVotes.entries()) {
      if (vote > maxVote) {
        maxVote = vote;
        topChar = char;
      }
    }
    resultChars.push(topChar);
  }

  const votedResult = resultChars.join('');
  const finalChosen = votedResult || topTextGroup[0];
  return stripEdgeNoiseHanziTokens(finalChosen);
}

/**
 * 6. [BoundaryRefiner]
 * Refines subtitle start and end timestamps precisely:
 * - Snaps frame entry/exit boundaries with pre-roll padding & frame-diffing transitions
 * - Ensures min display duration tailored to text reading speed
 * - Avoids artificial hard caps that create dead gaps between subtitles
 * - Bridges micro-gaps between consecutive lines
 * - Resolves overlapping boundaries without dropping subtitle content
 */
export function refineBoundaryTimestamps<T extends { startTime: number; endTime: number; originalText?: string; audioUrl?: string; duration?: number }>(
  subtitles: T[],
  _stepInterval: number = 0.5,
  transitionTimestamps?: number[]
): T[] {
  if (!subtitles || subtitles.length === 0) return [];

  const copy = subtitles.map((s) => ({ ...s }));
  copy.sort((a, b) => a.startTime - b.startTime);

  // Ripple pass for TTS audio duration: Ensure any item with audioUrl/duration pushes subsequent overlapping items forward
  for (let i = 0; i < copy.length - 1; i++) {
    const curr = copy[i];
    const currHasAudio = Boolean((curr as any).audioUrl || (curr as any).duration);
    if (currHasAudio) {
      const minNextStart = curr.endTime + 0.05;
      const next = copy[i + 1];
      if (next.startTime < minNextStart) {
        const shift = minNextStart - next.startTime;
        for (let k = i + 1; k < copy.length; k++) {
          copy[k].startTime = Number((copy[k].startTime + shift).toFixed(2));
          copy[k].endTime = Number((copy[k].endTime + shift).toFixed(2));
        }
      }
    }
  }

  const sortedTransitions = transitionTimestamps && transitionTimestamps.length > 0
    ? [...transitionTimestamps].sort((a, b) => a - b)
    : [];

  const findStartTransition = (timePoint: number, maxLookback: number = 0.35): number | null => {
    if (sortedTransitions.length === 0) return null;
    let bestT: number | null = null;
    let minDiff = maxLookback;

    for (const transT of sortedTransitions) {
      if (transT <= timePoint + 0.08) {
        const diff = timePoint - transT;
        if (diff >= -0.08 && diff <= minDiff) {
          minDiff = diff;
          bestT = transT;
        }
      }
    }
    return bestT;
  };

  const findEndTransition = (timePoint: number, maxLookahead: number = 0.35): number | null => {
    if (sortedTransitions.length === 0) return null;
    let bestT: number | null = null;
    let minDiff = maxLookahead;

    for (const transT of sortedTransitions) {
      if (transT >= timePoint - 0.08) {
        const diff = transT - timePoint;
        if (diff >= -0.08 && diff <= minDiff) {
          minDiff = diff;
          bestT = transT;
        }
      }
    }
    return bestT;
  };

  const refined: T[] = [];

  for (let i = 0; i < copy.length; i++) {
    const curr = copy[i];

    let startT = Math.max(0, curr.startTime);
    let endT = Math.max(startT + 0.20, curr.endTime);

    // Frame-diffing snap: Snap start time backward to closest visual onset transition if near (<= 0.35s)
    const snappedStart = findStartTransition(startT, 0.35);
    if (snappedStart !== null) {
      startT = snappedStart;
    }

    // Frame-diffing snap: Snap end time forward to closest visual exit transition if near (<= 0.35s)
    const snappedEnd = findEndTransition(endT, 0.35);
    if (snappedEnd !== null && snappedEnd > startT + 0.15) {
      endT = snappedEnd;
    }

    // Clamp endT so it NEVER extends past the next subtitle's start time (unless curr has TTS audio)
    if (i < copy.length - 1) {
      const next = copy[i + 1];
      if (next.startTime > startT) {
        const currHasAudio = Boolean((curr as any).audioUrl || (curr as any).duration);
        if (!currHasAudio) {
          endT = Math.min(endT, next.startTime - 0.02);
        }
      }
    }

    // Resolve overlap with previous subtitle: prev.endTime MUST yield to startT (Subtitle B's entry)
    if (refined.length > 0) {
      const prev = refined[refined.length - 1];
      const prevHasAudio = Boolean((prev as any).audioUrl || (prev as any).duration);
      if (prev.endTime >= startT) {
        if (prevHasAudio) {
          // Keep prev.endTime intact for full audio playback, shift startT forward
          startT = Number((prev.endTime + 0.05).toFixed(2));
          if (endT < startT + 0.20) endT = startT + 0.20;
        } else if (startT > prev.startTime + 0.02) {
          prev.endTime = Number(Math.max(prev.startTime + 0.05, startT - 0.02).toFixed(2));
        } else {
          prev.endTime = Number((prev.startTime + 0.10).toFixed(2));
          startT = Number((prev.endTime + 0.02).toFixed(2));
        }
      }
    }

    // Ensure minimum display duration (at least 0.20s)
    if (endT < startT + 0.20) {
      endT = startT + 0.20;
    }

    refined.push({
      ...curr,
      startTime: Number(startT.toFixed(2)),
      endTime: Number(endT.toFixed(2)),
    });
  }

  // Final Strict Non-Overlap Sanitizer Pass: Truncate prev.endTime unless prev has TTS audio
  for (let i = 1; i < refined.length; i++) {
    const prev = refined[i - 1];
    const curr = refined[i];
    const prevHasAudio = Boolean((prev as any).audioUrl || (prev as any).duration);

    if (prev.endTime >= curr.startTime) {
      if (prevHasAudio) {
        // Protect prev.endTime from audio cutoff by shifting curr forward
        const shift = Number((prev.endTime + 0.05 - curr.startTime).toFixed(2));
        if (shift > 0) {
          for (let k = i; k < refined.length; k++) {
            refined[k].startTime = Number((refined[k].startTime + shift).toFixed(2));
            refined[k].endTime = Number((refined[k].endTime + shift).toFixed(2));
          }
        }
      } else if (curr.startTime > prev.startTime + 0.02) {
        // Yield prev.endTime to curr.startTime without moving curr.startTime
        prev.endTime = Number(Math.max(prev.startTime + 0.05, curr.startTime - 0.02).toFixed(2));
      } else {
        prev.endTime = Number((prev.startTime + 0.10).toFixed(2));
        curr.startTime = Number((prev.endTime + 0.02).toFixed(2));
      }
      if (curr.endTime < curr.startTime + 0.20) {
        curr.endTime = Number((curr.startTime + 0.20).toFixed(2));
      }
    }
  }

  return refined;
}

/**
 * Master post-processing function that integrates all filters, multi-pass temporal clustering, and BoundaryRefiner
 */
export function refineAndMergeSubtitles(
  rawDetections: RawOcrItem[],
  stepInterval: number = 0.5,
  isLatinLanguage: boolean = true,
  transitionTimestamps?: number[],
  minConfidence: number = 0.70
): LocalOcrResult[] {
  if (!rawDetections || rawDetections.length === 0) return [];

  // Step A: Pre-filter candidate items
  // Adaptive continuation threshold: allows lower-confidence frames (e.g., 0.45 when minConfidence is 0.70)
  // to be included to prevent fragmenting or flickering subtitles.
  const continuationConfidenceThreshold = Math.max(0.25, minConfidence - 0.25);

  const rawCandidateItems: RawOcrItem[] = [];
  for (const item of rawDetections) {
    const itemConf = item.confidence ?? 0.88;
    // Allow candidates down to hysteresis continuation threshold
    if (itemConf < continuationConfidenceThreshold) continue;
    if (!applyWatermarkFilter(item.text, item.box)) continue;

    let text = correctOcrTextAnomalies(item.text);
    if (isLatinLanguage) {
      text = applyLatinFilter(text, true);
    } else {
      text = stripEmbeddedNoiseTokens(text);
    }

    if (!applyHardFilter(text, itemConf, continuationConfidenceThreshold, !isLatinLanguage)) continue;
    if (!applySingleCjkFilter(text, !isLatinLanguage)) continue;

    if (text.length > 0) {
      rawCandidateItems.push({ ...item, text });
    }
  }

  rawCandidateItems.sort((a, b) => a.timestamp - b.timestamp);

  const halfStep = Math.max(0.05, stepInterval / 2);

  // Step B: Group consecutive frame detections using Hysteresis confidence + character overlap + majority voting
  interface SubGroupItem {
    text: string;
    confidence?: number;
  }
  interface SubGroup {
    readings: SubGroupItem[];
    timestamps: number[];
  }

  const groups: SubGroup[] = [];
  const assignedTimestamps = new Set<number>();

  for (const item of rawCandidateItems) {
    const itemConf = item.confidence ?? 0.88;
    const readingObj = { text: item.text, confidence: item.confidence };

    const newGroupMinConf = continuationConfidenceThreshold;

    if (groups.length === 0) {
      if (itemConf >= newGroupMinConf) {
        groups.push({ readings: [readingObj], timestamps: [item.timestamp] });
        assignedTimestamps.add(item.timestamp);
      }
      continue;
    }

    const lastGroup = groups[groups.length - 1];
    const lastT = lastGroup.timestamps[lastGroup.timestamps.length - 1];
    const timeGap = item.timestamp - lastT;

    const currentBestText = pickBestReadingWithConfidence(lastGroup.readings);
    const maxAllowedGap = Math.min(0.80, Math.max(0.35, stepInterval * 2.0));

    // Prevent bridging across scene cuts if transitionTimestamps are detected
    const hasSceneCut = transitionTimestamps?.some((t) => t > lastT && t <= item.timestamp);

    // Hysteresis continuation check: check against currentBestText or recent readings
    const isMatchingActiveLine = !hasSceneCut && (
      isSameSubtitleLine(currentBestText, item.text, timeGap) ||
      lastGroup.readings.slice(-3).some(r => isSameSubtitleLine(r.text, item.text, timeGap))
    );

    if (timeGap <= maxAllowedGap && isMatchingActiveLine) {
      // Continuous line bridge
      lastGroup.timestamps.push(item.timestamp);
      lastGroup.readings.push(readingObj);
      assignedTimestamps.add(item.timestamp);
    } else {
      // New potential line accepts candidate items down to continuation threshold
      if (itemConf >= newGroupMinConf) {
        groups.push({ readings: [readingObj], timestamps: [item.timestamp] });
        assignedTimestamps.add(item.timestamp);
      }
    }
  }

  // Step C: Convert groups to raw timing items with majority voting & confidence-weighted selection
  // Enforce high-level primary threshold filtering (minConfidence) with temporal safety
  const mergedSubtitles: LocalOcrResult[] = [];

  for (let i = 0; i < groups.length; i++) {
    const group = groups[i];
    
    // Evaluate group validity: at least one frame must hit the primary minConfidence threshold,
    // or the average confidence must be high, or it must be persistent (>=3 frames) indicating highly consistent signal.
    const groupConfs = group.readings.map(r => r.confidence ?? 0.88);
    const maxConfInGroup = Math.max(...groupConfs);
    const avgConfInGroup = groupConfs.length > 0 ? groupConfs.reduce((sum, c) => sum + c, 0) / groupConfs.length : 0.0;
    
    const isGroupAccepted = maxConfInGroup >= minConfidence || 
                           avgConfInGroup >= minConfidence ||
                           (group.readings.length >= 3 && avgConfInGroup >= Math.max(0.30, minConfidence - 0.15));
                           
    if (!isGroupAccepted) {
      // Free these timestamps so they can potentially be recovered by Step C2 if they reside in a long window
      group.timestamps.forEach(t => assignedTimestamps.delete(t));
      continue;
    }

    const firstT = group.timestamps[0];
    const lastT = group.timestamps[group.timestamps.length - 1];

    const startTime = Math.max(0, firstT - halfStep);
    const endTime = lastT + halfStep;
    const finalBestText = pickBestReadingWithConfidence(group.readings);

    mergedSubtitles.push({
      startTime: Number(startTime.toFixed(2)),
      endTime: Number(endTime.toFixed(2)),
      originalText: finalBestText,
      sourceLang: 'PaddleOCR PP-OCRv6 Tiny',
      confidence: Number(avgConfInGroup.toFixed(4)),
    });
  }

  // Step C2: Long Window (>1.5s) Fallback Recovery
  // If a time window had OCR detections but all were rejected under minConfidence,
  // recover the best available reading from the rejected cluster instead of dropping the line completely.
  const rejectedItems = rawDetections.filter((item) => {
    if (assignedTimestamps.has(item.timestamp)) return false;
    if (!item.text || item.text.trim().length === 0) return false;
    if (!applyWatermarkFilter(item.text, item.box)) return false;

    let txt = correctOcrTextAnomalies(item.text);
    if (isLatinLanguage) {
      txt = applyLatinFilter(txt, true);
    } else {
      txt = stripEmbeddedNoiseTokens(txt);
    }

    if (!applyHardFilter(txt, item.confidence ?? 0.35, 0.20, !isLatinLanguage)) return false;
    if (!applySingleCjkFilter(txt, !isLatinLanguage)) return false;
    return true;
  });

  if (rejectedItems.length > 0) {
    rejectedItems.sort((a, b) => a.timestamp - b.timestamp);

    let currentCluster: RawOcrItem[] = [];
    const maxGap = Math.max(1.2, stepInterval * 2.5);

    for (const item of rejectedItems) {
      if (currentCluster.length === 0) {
        currentCluster.push(item);
      } else {
        const prevT = currentCluster[currentCluster.length - 1].timestamp;
        if (item.timestamp - prevT <= maxGap) {
          currentCluster.push(item);
        } else {
          processRejectedCluster(currentCluster);
          currentCluster = [item];
        }
      }
    }
    if (currentCluster.length > 0) {
      processRejectedCluster(currentCluster);
    }
  }

  function processRejectedCluster(cluster: RawOcrItem[]) {
    if (cluster.length === 0) return;
    const firstT = cluster[0].timestamp;
    const lastT = cluster[cluster.length - 1].timestamp;

    // Recover short interjections or dialogue lines (even single/double-frame clusters >= 1 frame)
    if (cluster.length >= 1) {
      const readings = cluster.map((c) => {
        let txt = correctOcrTextAnomalies(c.text);
        if (isLatinLanguage) {
          txt = applyLatinFilter(txt, true);
        } else {
          txt = stripEmbeddedNoiseTokens(txt);
        }
        return {
          text: txt,
          confidence: c.confidence ?? 0.35,
        };
      }).filter(r => r.text && r.text.length > 0 && applyHardFilter(r.text, r.confidence, 0.20, !isLatinLanguage));

      if (readings.length === 0) return;

      const bestText = pickBestReadingWithConfidence(readings);

      if (bestText && bestText.trim().length > 0 && applyHardFilter(bestText, 0.35, 0.20, !isLatinLanguage)) {
        const startTime = Math.max(0, firstT - halfStep);
        const endTime = Math.max(startTime + 0.35, lastT + halfStep);

        // Check if there is an existing subtitle with the exact/similar text within a ±5.0 seconds window or overlapping
        const existsDuplicateOverlap = mergedSubtitles.some((m) => {
          const isSameText = isSameSubtitleLine(m.originalText || '', bestText, 0);
          if (isSameText) return true;

          const timeGap = Math.max(0, Math.max(m.startTime, startTime) - Math.min(m.endTime, endTime));
          const hasOverlap = Math.min(m.endTime, endTime) - Math.max(m.startTime, startTime) > 0;
          return hasOverlap || timeGap <= 5.0;
        });

        if (!existsDuplicateOverlap) {
          const confs = readings.map(r => r.confidence ?? 0.35);
          const avgConfidence = confs.length > 0 ? confs.reduce((sum, c) => sum + c, 0) / confs.length : 0.35;

          mergedSubtitles.push({
            startTime: Number(startTime.toFixed(2)),
            endTime: Number(endTime.toFixed(2)),
            originalText: bestText,
            sourceLang: 'PaddleOCR PP-OCRv6 Tiny (Fallback)',
            confidence: Number(avgConfidence.toFixed(4)),
          });
        }
      }
    }
  }

  // Ensure mergedSubtitles are sorted chronologically
  mergedSubtitles.sort((a, b) => a.startTime - b.startTime);

  // Step D: Thuật toán Hậu Xử Lý "Nối Luồng" (Gap-Filling & Interpolation)
  // Max allowed gap between subtitle lines: max_merge_gap = 0.50s (expanded to 0.80s for flickers < 0.6s)
  // If line A ends and line B starts within max gap, check Levenshtein similarity / character overlap (> 75%).
  // Interpolates & bridges the gap smoothly to eliminate micro-gaps and subtitle flickering caused by missed frames.
  const pass2: LocalOcrResult[] = [];
  for (const curr of mergedSubtitles) {
    if (pass2.length === 0) {
      pass2.push({ ...curr });
      continue;
    }

    const prev = pass2[pass2.length - 1];
    const timeGap = curr.startTime - prev.endTime;
    const hasShotCut = transitionTimestamps?.some((t) => t >= prev.endTime - 0.1 && t <= curr.startTime + 0.1);

    const prevClean = stripEmbeddedNoiseTokens(prev.originalText || '').trim();
    const currClean = stripEmbeddedNoiseTokens(curr.originalText || '').trim();

    const textSim = getTextSimilarityScore(prevClean || prev.originalText || '', currClean || curr.originalText || '');
    const charSim = getCharacterOverlapRatio(prevClean || prev.originalText || '', currClean || curr.originalText || '');
    const isHighSimilarity = textSim >= 0.75 || charSim >= 0.60 || isSameSubtitleLine(prev.originalText || '', curr.originalText || '', Math.max(0, timeGap));

    const prevDuration = prev.endTime - prev.startTime;
    const currDuration = curr.endTime - curr.startTime;
    const isFlicker = prevDuration < 0.60 || currDuration < 0.60;
    const dynamicMaxGap = isFlicker ? 0.80 : 0.50;

    if (!hasShotCut && timeGap <= dynamicMaxGap && isHighSimilarity) {
      // Seamlessly bridge / interpolate gap between line A and line B
      prev.startTime = Math.min(prev.startTime, curr.startTime);
      prev.endTime = Math.max(prev.endTime, curr.endTime);
      prev.originalText = selectBestOcrText(prev.originalText || '', curr.originalText || '');
    } else {
      pass2.push({ ...curr });
    }
  }

  // Step E: Filter out micro-flickers & empty noise (< 0.15s duration with single non-word character)
  const filtered = pass2.filter((sub) => {
    const duration = sub.endTime - sub.startTime;
    const textLen = (sub.originalText || '').trim().length;
    // Only drop if duration is extremely brief (< 0.15s) AND contains no alphanumeric word letters
    if (duration < 0.15 && textLen <= 1 && !/[\p{L}\p{N}]/u.test(sub.originalText || '')) {
      return false; // Drop single-frame isolated noise symbol
    }
    return true;
  });

  // Step F: Apply [BoundaryRefiner] for exact timestamp precision & duration alignment
  const refined = refineBoundaryTimestamps(filtered, stepInterval, transitionTimestamps);

  // Final Edge Noise Sanitization Pass
  return refined
    .map((sub) => {
      let text = sub.originalText || '';
      if (!isLatinLanguage) {
        text = stripEdgeNoiseHanziTokens(stripEmbeddedNoiseTokens(text)).trim();
      }
      return {
        ...sub,
        originalText: text,
      };
    })
    .filter((sub) => (sub.originalText || '').trim().length > 0);
}

/**
 * 8. [Dedup] GeminiSubtitleDeduplicator
 * Performs high-level LLM semantic deduplication and sentence joining using Gemini API
 */
export async function deduplicateSubtitlesWithGemini(
  subtitles: LocalOcrResult[],
  apiKey?: string,
  modelName: string = 'gemini-3.6-flash',
  targetLang: string = 'Tiếng Việt'
): Promise<LocalOcrResult[]> {
  if (!subtitles || subtitles.length === 0) return subtitles;

  try {
    const response = await fetch('/api/deduplicate-subtitles', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        subtitles,
        model: modelName,
        targetLang,
        apiKey,
      }),
    });

    if (!response.ok) return subtitles;
    const rawText = await response.text().catch(() => '');
    let data: any = null;
    try {
      data = JSON.parse(rawText);
    } catch {
      return subtitles;
    }

    if (data && data.success && Array.isArray(data.subtitles) && data.subtitles.length > 0) {
      return data.subtitles;
    }
  } catch (err) {
    console.warn('deduplicateSubtitlesWithGemini exception:', err);
  }

  return subtitles;
}

