import { SubtitleItem, SubtitleStyleConfig, BlurOverlay, LogoOverlay, TextOverlay } from '../types';
import { wrapSubtitleText } from './srtParser';
import { generateVoiceoverAudioBuffer } from './audioExporter';
import { createFile as createMp4BoxFile, DataStream } from 'mp4box';
import fixWebmDuration from 'fix-webm-duration';
import { loadAllSavedCustomFonts, getSavedCustomFonts } from './fontStorage';
import {
  Input,
  ALL_FORMATS,
  BufferSource,
  BufferTarget,
  Output,
  Mp4OutputFormat,
  CanvasSink,
  CanvasSource,
  AudioBufferSource,
  getFirstEncodableVideoCodec,
  getFirstEncodableAudioCodec,
} from 'mediabunny';

function createMp4File() {
  return createMp4BoxFile();
}

/**
 * Fixes duration metadata in MP4 files (mvhd, tkhd, mdhd, mehd boxes)
 * generated by MediaRecorder or encoders that omit or zero duration metadata.
 */
export async function fixMp4Duration(blob: Blob, durationInSeconds: number): Promise<Blob> {
  if (!durationInSeconds || durationInSeconds <= 0) return blob;

  try {
    const arrayBuffer = await blob.arrayBuffer();
    const bytes = new Uint8Array(arrayBuffer);
    const view = new DataView(arrayBuffer);

    let movieTimescale = 1000;

    function scanBoxes(start: number, end: number) {
      let pos = start;
      while (pos + 8 <= end) {
        let boxSize = view.getUint32(pos);
        const boxType = String.fromCharCode(
          bytes[pos + 4],
          bytes[pos + 5],
          bytes[pos + 6],
          bytes[pos + 7]
        );

        let headerSize = 8;
        if (boxSize === 1) {
          if (pos + 16 > end) break;
          const high = view.getUint32(pos + 8);
          const low = view.getUint32(pos + 12);
          boxSize = high * 4294967296 + low;
          headerSize = 16;
        } else if (boxSize === 0) {
          boxSize = end - pos;
        }

        if (boxSize < headerSize || pos + boxSize > end) {
          break;
        }

        const payloadStart = pos + headerSize;
        const payloadEnd = pos + boxSize;

        if (
          boxType === 'moov' ||
          boxType === 'trak' ||
          boxType === 'mdia' ||
          boxType === 'minf' ||
          boxType === 'mvex'
        ) {
          scanBoxes(payloadStart, payloadEnd);
        } else if (boxType === 'mvhd') {
          const version = bytes[payloadStart];
          let timescaleOffset = payloadStart + 12;
          let durationOffset = payloadStart + 16;
          if (version === 1) {
            timescaleOffset = payloadStart + 20;
            durationOffset = payloadStart + 24;
          }
          if (timescaleOffset + 4 <= payloadEnd) {
            movieTimescale = view.getUint32(timescaleOffset) || 1000;
          }
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'tkhd') {
          const version = bytes[payloadStart];
          let durationOffset = payloadStart + 20;
          if (version === 1) {
            durationOffset = payloadStart + 28;
          }
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'mdhd') {
          const version = bytes[payloadStart];
          let timescaleOffset = payloadStart + 12;
          let durationOffset = payloadStart + 16;
          if (version === 1) {
            timescaleOffset = payloadStart + 20;
            durationOffset = payloadStart + 24;
          }
          let mediaTimescale = movieTimescale;
          if (timescaleOffset + 4 <= payloadEnd) {
            mediaTimescale = view.getUint32(timescaleOffset) || movieTimescale;
          }
          const targetDurationUnits = Math.round(durationInSeconds * mediaTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'mehd') {
          const version = bytes[payloadStart];
          const durationOffset = payloadStart + 4;
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        }

        pos += boxSize;
      }
    }

    scanBoxes(0, bytes.length);
    return new Blob([bytes.buffer], { type: blob.type || 'video/mp4' });
  } catch (err) {
    console.warn('[fixMp4Duration] Failed to patch MP4 duration:', err);
    return blob;
  }
}

/**
 * Adjusts volume of an AudioBuffer using OfflineAudioContext.
 */
async function adjustAudioBufferVolume(
  original: AudioBuffer | null,
  volume: number = 1.0,
  targetDuration: number
): Promise<AudioBuffer | null> {
  if (!original) return null;
  if (volume === 0) return null; // Muted
  if (volume === 1.0) return original; // No change needed

  const sampleRate = original.sampleRate;
  const numChannels = original.numberOfChannels;
  const duration = Math.max(original.duration, targetDuration);

  const offlineCtx = new OfflineAudioContext(
    numChannels,
    Math.ceil(sampleRate * duration),
    sampleRate
  );

  const originalSource = offlineCtx.createBufferSource();
  originalSource.buffer = original;

  const gainNode = offlineCtx.createGain();
  gainNode.gain.value = volume;

  originalSource.connect(gainNode);
  gainNode.connect(offlineCtx.destination);
  originalSource.start(0);

  return await offlineCtx.startRendering();
}

/**
 * Mixes original video audio and TTS voiceover audio together.
 */
async function mixAudioBuffers(
  original: AudioBuffer | null,
  tts: AudioBuffer | null,
  targetDuration: number,
  videoVolume: number = 1.0
): Promise<AudioBuffer | null> {
  if (!original && !tts) return null;
  if (original && !tts) {
    return await adjustAudioBufferVolume(original, videoVolume, targetDuration);
  }
  if (!original && tts) return tts;

  // Both original and TTS exist
  if (videoVolume === 0) {
    return tts;
  }

  const sampleRate = original!.sampleRate;
  const numChannels = Math.max(original!.numberOfChannels, tts!.numberOfChannels);
  const duration = Math.max(original!.duration, tts!.duration, targetDuration);

  const offlineCtx = new OfflineAudioContext(
    numChannels,
    Math.ceil(sampleRate * duration),
    sampleRate
  );

  // 1. Play original audio with videoVolume applied
  const originalSource = offlineCtx.createBufferSource();
  originalSource.buffer = original!;

  if (videoVolume !== 1.0) {
    const gainNode = offlineCtx.createGain();
    gainNode.gain.value = videoVolume;
    originalSource.connect(gainNode);
    gainNode.connect(offlineCtx.destination);
  } else {
    originalSource.connect(offlineCtx.destination);
  }
  originalSource.start(0);

  // 2. Play TTS audio (mono will be automatically upmixed to stereo/numChannels)
  const ttsSource = offlineCtx.createBufferSource();
  ttsSource.buffer = tts!;
  ttsSource.connect(offlineCtx.destination);
  ttsSource.start(0);

  return await offlineCtx.startRendering();
}

export interface RenderProgress {
  percentage: number;
  currentTime: number;
  duration: number;
  status: string;
}

/**
 * Draws current video frame and burning subtitle overlay onto the 2D Canvas context.
 */
function wrapCanvasText(
  context: CanvasRenderingContext2D,
  text: string,
  maxWidth: number
): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = '';

  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    const testLine = currentLine ? currentLine + ' ' + word : word;
    const metrics = context.measureText(testLine);
    if (metrics.width > maxWidth && i > 0) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) {
    lines.push(currentLine);
  }
  return lines;
}

function getBgColorWithOpacity(hexColor: string, opacity: number = 65): string {
  if (!hexColor) return `rgba(0, 0, 0, ${opacity / 100})`;
  if (hexColor.startsWith('rgba')) return hexColor;
  let hex = hexColor.replace('#', '');
  if (hex.length === 3) hex = hex.split('').map(x => x + x).join('');
  const num = parseInt(hex, 16);
  if (isNaN(num)) return `rgba(0, 0, 0, ${opacity / 100})`;
  const r = (num >> 16) & 255;
  const g = (num >> 8) & 255;
  const b = num & 255;
  return `rgba(${r}, ${g}, ${b}, ${(opacity / 100).toFixed(2)})`;
}

export function drawSubtitleOverlay(
  ctx: CanvasRenderingContext2D,
  video: HTMLVideoElement | HTMLCanvasElement | OffscreenCanvas | ImageBitmap | VideoFrame,
  vWidth: number,
  vHeight: number,
  curTime: number,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  blurOverlays: BlurOverlay[] = [],
  logoOverlays: LogoOverlay[] = [],
  textOverlays: TextOverlay[] = [],
  logoBitmaps: Record<string, HTMLImageElement | ImageBitmap> = {}
) {
  // 1. Draw base video frame
  ctx.drawImage(video, 0, 0, vWidth, vHeight);

  // 1b. Render Blur Overlays
  blurOverlays.forEach((blur) => {
    try {
      ctx.save();
      ctx.beginPath();
      const x = (blur.x / 100) * vWidth;
      const y = (blur.y / 100) * vHeight;
      const w = (blur.width / 100) * vWidth;
      const h = (blur.height / 100) * vHeight;
      const r = (blur.borderRadius || 0) * (vHeight / 720);
      if (typeof ctx.roundRect === 'function') {
        ctx.roundRect(x, y, w, h, r);
      } else {
        ctx.rect(x, y, w, h);
      }
      ctx.clip();
      ctx.filter = `blur(${blur.blur * (vHeight / 720)}px)`;
      ctx.drawImage(video, 0, 0, vWidth, vHeight);
      ctx.restore();
    } catch (err) {
      console.warn('[VideoRenderer] Blur overlay draw warning:', err);
    }
  });

  // 1c. Render Logo Overlays
  logoOverlays.forEach((logo) => {
    const x = (logo.x / 100) * vWidth;
    const y = (logo.y / 100) * vHeight;
    const w = (logo.width / 100) * vWidth;
    const h = (logo.height / 100) * vHeight;
    const r = (logo.borderRadius || 0) * (vHeight / 720);
    const img = logoBitmaps[logo.id] || logoBitmaps[logo.url];
    if (img) {
      ctx.save();
      ctx.globalAlpha = Math.max(0, Math.min(1, (logo.opacity ?? 100) / 100));
      if (r > 0) {
        ctx.beginPath();
        if (typeof ctx.roundRect === 'function') {
          ctx.roundRect(x, y, w, h, r);
        } else {
          ctx.rect(x, y, w, h);
        }
        ctx.clip();
      }
      ctx.drawImage(img, x, y, w, h);
      ctx.restore();
    }
  });

  // 1d. Render Text Overlays (Cấu hình riêng biệt với phụ đề, KHÔNG mặc định nền đen)
  textOverlays.forEach((textItem) => {
    const x = (textItem.x / 100) * vWidth;
    const y = (textItem.y / 100) * vHeight;
    const w = (textItem.width / 100) * vWidth;
    const h = (textItem.height / 100) * vHeight;
    const scaleFactor = vHeight / 720;

    ctx.save();
    ctx.globalAlpha = Math.max(0, Math.min(1, (textItem.opacity ?? 100) / 100));

    // Nền hộp chữ (chỉ vẽ khi bật hasBackground và backgroundColor hợp lệ)
    if (textItem.hasBackground && textItem.backgroundColor && textItem.backgroundColor !== 'transparent') {
      const bgOpacity = (textItem.backgroundOpacity ?? 80) / 100;
      ctx.fillStyle = getBgColorWithOpacity(textItem.backgroundColor, bgOpacity);
      const bgRadius = (textItem.borderRadius || 0) * scaleFactor;
      ctx.beginPath();
      if (typeof ctx.roundRect === 'function') {
        ctx.roundRect(x, y, w, h, bgRadius);
      } else {
        ctx.rect(x, y, w, h);
      }
      ctx.fill();
    }

    // Font chữ riêng biệt
    const fontSize = Math.max(8, Math.round((textItem.fontSize || 28) * scaleFactor));
    const fontFamily = textItem.fontFamily || 'Be Vietnam Pro, sans-serif';
    const fontWeight = textItem.fontWeight || 'bold';
    const fontStyle = textItem.fontStyle || 'normal';
    ctx.font = `${fontStyle} ${fontWeight} ${fontSize}px ${fontFamily}`;

    // Căn lề
    const align = textItem.textAlign || 'center';
    ctx.textAlign = align;
    ctx.textBaseline = 'middle';

    const padding = 8 * scaleFactor;
    const maxTextWidth = Math.max(10, w - padding * 2);
    const textLines = wrapCanvasText(ctx, textItem.text || '', maxTextWidth);
    const textLineHeight = fontSize * 1.25;
    const totalTextHeight = textLines.length * textLineHeight;
    const startY = y + h / 2 - (totalTextHeight - textLineHeight) / 2;

    let drawX = x + w / 2;
    if (align === 'left') drawX = x + padding;
    else if (align === 'right') drawX = x + w - padding;

    textLines.forEach((line, idx) => {
      const lineY = startY + idx * textLineHeight;

      // Đổ bóng chữ riêng (Text Shadow / Glow)
      if (textItem.textShadow && textItem.shadowColor) {
        ctx.save();
        ctx.shadowColor = textItem.shadowColor;
        ctx.shadowBlur = (textItem.shadowBlur ?? 8) * scaleFactor;
        ctx.fillStyle = textItem.color || '#ffffff';
        ctx.fillText(line, drawX, lineY);
        ctx.restore();
      }

      // Viền chữ riêng (Text Outline / Stroke)
      if (textItem.textOutline && textItem.outlineWidth && textItem.outlineWidth > 0) {
        ctx.strokeStyle = textItem.outlineColor || '#000000';
        ctx.lineWidth = Math.max(0.5, textItem.outlineWidth * 2 * scaleFactor);
        ctx.lineJoin = 'round';
        ctx.miterLimit = 2;
        ctx.strokeText(line, drawX, lineY);
      }

      // Màu chữ chính
      ctx.fillStyle = textItem.color || '#ffffff';
      ctx.fillText(line, drawX, lineY);
    });

    ctx.restore();
  });

  // 2. Mask original subtitles if requested
  if (styleConfig.maskOriginalSubtitles) {
    ctx.fillStyle = styleConfig.maskColor || 'rgba(0, 0, 0, 0.75)';
    const maskY =
      vHeight * (1 - (styleConfig.bottomOffsetPercentage || 12) / 100) -
      vHeight * 0.08;
    const maskH = vHeight * 0.14;
    ctx.fillRect(0, Math.max(0, maskY), vWidth, maskH);
  }

  // 3. Find active subtitle item
  const activeSub = subtitles.find(
    (s) => curTime >= s.startTime && curTime <= s.endTime
  );

  if (!activeSub) return;

  let rawText = activeSub.translatedText || activeSub.originalText || '';

  // Apply text transformation (casing)
  if (styleConfig.textTransform === 'uppercase') {
    rawText = rawText.toUpperCase();
  } else if (styleConfig.textTransform === 'lowercase') {
    rawText = rawText.toLowerCase();
  } else if (styleConfig.textTransform === 'capitalize') {
    rawText = rawText.replace(/\b\w/g, (c) => c.toUpperCase());
  }

  // Align style configurations & fallback defaults with VideoPlayer.tsx perfectly
  const defaultFontSize = styleConfig.fontSize || 22;
  const defaultPadding = styleConfig.padding || 6;
  const defaultBorderRadius = styleConfig.borderRadius ?? 8;
  const bgOpacity = styleConfig.bgOpacity ?? 65;

  // Calculate font size relative to standard 720p height
  const scaleFactor = vHeight / 720;
  const baseFontSize = defaultFontSize * scaleFactor;
  // Proportional minimum font size (10px on 360p corresponds to 20px on 720p)
  const minFontSize = Math.max(12, Math.round(20 * scaleFactor));
  const fontSize = Math.max(minFontSize, Math.round(baseFontSize));

  const fontFamily = styleConfig.fontFamily || 'system-ui, sans-serif';
  const fontWeight = styleConfig.fontWeight || 'bold';
  const fontStyle = styleConfig.fontStyle || 'normal';

  ctx.font = `${fontStyle} ${fontWeight} ${fontSize}px ${fontFamily}`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';

  const lineHeight = fontSize * 1.35;
  const padding = defaultPadding * scaleFactor;

  // Align subtitle positioning with VideoPlayer preview 100%
  const displayBox = activeSub.boundingBox || (styleConfig as any).roi || { x: 10, y: 76, width: 80, height: 20 };
  
  const parentX = (displayBox.x / 100) * vWidth;
  const parentY = (displayBox.y / 100) * vHeight;
  const parentWidth = (displayBox.width / 100) * vWidth;
  const parentHeight = (displayBox.height / 100) * vHeight;

  // Word wrap based on bounding box width
  const wrapWidth = Math.max(40, parentWidth - padding * 2.5);
  const lines = wrapCanvasText(ctx, rawText, wrapWidth);
  if (!lines || lines.length === 0) return;

  // Calculate actual content dimensions
  let maxLineWidth = 0;
  lines.forEach((line) => {
    const w = ctx.measureText(line).width;
    if (w > maxLineWidth) maxLineWidth = w;
  });

  const totalTextHeight = lines.length * lineHeight;
  const boxWidth = Math.min(parentWidth, maxLineWidth + padding * 2.5);
  const boxHeight = Math.max(parentHeight, totalTextHeight + padding * 1.5);

  // Exact center of the bounding box
  const centerX = parentX + parentWidth / 2;
  const centerY = parentY + parentHeight / 2;

  const boxX = centerX - boxWidth / 2;
  const boxY = centerY - boxHeight / 2;

  // Draw Subtitle Background Box with proper alpha/opacity parsing
  if (styleConfig.hasBackground !== false && styleConfig.backgroundColor) {
    ctx.fillStyle = getBgColorWithOpacity(styleConfig.backgroundColor, bgOpacity);
    const radius = defaultBorderRadius * scaleFactor;

    ctx.beginPath();
    if (typeof ctx.roundRect === 'function') {
      ctx.roundRect(boxX, boxY, boxWidth, boxHeight, radius);
    } else {
      ctx.rect(boxX, boxY, boxWidth, boxHeight);
    }
    ctx.fill();
  }

  // Draw Text Lines centered inside box
  const startY = centerY - ((lines.length - 1) * lineHeight) / 2;
  const drawX = centerX;

  lines.forEach((line, idx) => {
    const lineY = startY + idx * lineHeight;

    // 1. Text Shadow / Glow
    if (styleConfig.textShadowColor) {
      ctx.save();
      ctx.shadowColor = styleConfig.textShadowColor;
      ctx.shadowBlur = (styleConfig.textShadowBlur ?? 8) * scaleFactor;
      ctx.shadowOffsetX = (styleConfig.textShadowOffsetX ?? 0) * scaleFactor;
      ctx.shadowOffsetY = (styleConfig.textShadowOffsetY ?? 2) * scaleFactor;
      ctx.fillStyle = styleConfig.fontColor || '#ffffff';
      ctx.fillText(line, drawX, lineY);
      ctx.restore();
    } else if (styleConfig.textOutline !== false) {
      ctx.save();
      ctx.shadowColor = 'rgba(0,0,0,0.85)';
      ctx.shadowBlur = 6 * scaleFactor;
      ctx.shadowOffsetY = 3 * scaleFactor;
      ctx.fillStyle = styleConfig.fontColor || '#ffffff';
      ctx.fillText(line, drawX, lineY);
      ctx.restore();
    }

    // 2. Secondary Text Outline (Viền kép / Outer sticker border)
    const hasSecOutline = styleConfig.hasSecondaryOutline === true ||
      (typeof styleConfig.secondaryOutlineWidth === 'number' && styleConfig.secondaryOutlineWidth > 0 && styleConfig.hasSecondaryOutline !== false);
    const secOutlineWidth = hasSecOutline ? Math.max(0, styleConfig.secondaryOutlineWidth ?? 4) : 0;
    const primOutlineWidth = (styleConfig.textOutline !== false) ? Math.max(0, styleConfig.outlineWidth ?? 3) : 0;

    if (secOutlineWidth > 0) {
      const totalSecStroke = Math.max(0.5, (primOutlineWidth + secOutlineWidth) * 2 * scaleFactor);
      ctx.strokeStyle = styleConfig.secondaryOutlineColor || '#000000';
      ctx.lineWidth = totalSecStroke;
      ctx.lineJoin = 'round';
      ctx.miterLimit = 2;
      ctx.strokeText(line, drawX, lineY);
    }

    // 3. Primary Text Outline (Stroke)
    if (styleConfig.textOutline !== false && primOutlineWidth > 0) {
      ctx.strokeStyle = styleConfig.outlineColor || '#000000';
      ctx.lineWidth = Math.max(0.5, primOutlineWidth * 2 * scaleFactor);
      ctx.lineJoin = 'round';
      ctx.miterLimit = 2;
      ctx.strokeText(line, drawX, lineY);
    }

    // 4. Main Text Fill
    ctx.fillStyle = styleConfig.fontColor || '#ffffff';
    ctx.fillText(line, drawX, lineY);
  });
}

/**
 * Renders video with subtitles using Mediabunny CanvasSink, CanvasSource, AudioBufferSource, and Mp4OutputFormat.
 * Guarantees zero tearing, perfect PTS/DTS sync, and hardware-accelerated encoding with fallback.
 */
export async function renderWithMp4Muxer(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
  } = {},
  preferSoftware = false
): Promise<Blob> {
  if (typeof VideoEncoder === 'undefined') {
    throw new Error('WebCodecs VideoEncoder không được hỗ trợ trên trình duyệt này.');
  }

  // Preload and ensure all fonts (Google Fonts & custom uploaded fonts) are ready
  try {
    await loadAllSavedCustomFonts();
    if (typeof document !== 'undefined' && document.fonts) {
      await document.fonts.ready;
    }
  } catch (_fontErr) {}

  if (!styleConfig.customUploadedFonts || styleConfig.customUploadedFonts.length === 0) {
    const savedFonts = getSavedCustomFonts();
    if (savedFonts.length > 0) {
      styleConfig = {
        ...styleConfig,
        customUploadedFonts: savedFonts
          .filter((f) => f.dataUrl)
          .map((f) => ({
            family: f.value.split(',')[0].replace(/['"]/g, '').trim(),
            dataUrl: f.dataUrl!,
          })),
      };
    }
  }

  // 1. Fetch the video as an ArrayBuffer
  let arrayBuffer: ArrayBuffer;
  try {
    const res = await fetch(videoUrl);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    arrayBuffer = await res.arrayBuffer();
  } catch (err) {
    throw new Error(`CORS hoặc network error khi tải video: ${String(err)}`);
  }

  // 2. Preload Logo Overlays
  const logoBitmaps = await preloadLogoOverlays(options.logoOverlays || []);

  // 3. Demux video using Mediabunny Input
  const input = new Input({
    formats: ALL_FORMATS,
    source: new BufferSource(arrayBuffer),
  });

  const videoTrack = await input.getPrimaryVideoTrack();
  if (!videoTrack) {
    throw new Error('Không tìm thấy luồng Video Track trong tệp video nguồn.');
  }

  const rawDuration = await input.computeDuration();
  const duration = rawDuration || 10;
  const packetStats = await videoTrack.computePacketStats(150);

  let videoFps = (packetStats && packetStats.averagePacketRate > 0)
    ? packetStats.averagePacketRate
    : 30;

  if (!videoFps || !isFinite(videoFps) || videoFps <= 5 || videoFps > 120) {
    videoFps = Math.max(10, Math.min(60, (packetStats?.packetCount || 0) / duration)) || 30;
  }

  const totalFrames = (packetStats && packetStats.packetCount > 0)
    ? packetStats.packetCount
    : Math.max(1, Math.round(duration * videoFps));

  const toEven = (val: number) => Math.max(2, Math.floor(val / 2) * 2);
  const trackWidth = videoTrack.displayWidth || videoTrack.codedWidth || 1280;
  const trackHeight = videoTrack.displayHeight || videoTrack.codedHeight || 720;
  const vWidth = toEven(trackWidth);
  const vHeight = toEven(trackHeight);

  // 4. Decode Original Audio (if present)
  let originalAudioBuffer: AudioBuffer | null = null;
  try {
    const actx = new (window.AudioContext || (window as any).webkitAudioContext)();
    const decodeBuf = arrayBuffer.slice(0);
    originalAudioBuffer = await actx.decodeAudioData(decodeBuf);
    await actx.close();
  } catch (e) {
    console.warn('Không có hoặc không thể nạp audio track gốc:', e);
  }

  // 5. Generate or Mix Audio
  const videoVolume = options.videoVolume ?? 1.0;
  let audioBuffer: AudioBuffer | null = null;
  if (options.includeVoiceover) {
    try {
      const result = await generateVoiceoverAudioBuffer(
        subtitles,
        duration,
        options.ttsSpeed || 1.0,
        options.ttsPitch || 0
      );
      const ttsAudioBuffer = result.buffer;
      audioBuffer = await mixAudioBuffers(originalAudioBuffer, ttsAudioBuffer, duration, videoVolume);
    } catch (e: any) {
      console.warn('Không thể dựng audio thuyết minh, sẽ dùng audio gốc làm fallback:', e);
      audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
    }
  } else {
    audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
  }

  // 6. Setup Mediabunny Output, BufferTarget, CanvasSink & CanvasSource
  const target = new BufferTarget();
  const output = new Output({
    format: new Mp4OutputFormat({ fastStart: 'in-memory' }),
    target,
  });

  const getDynamicBitrate = (width: number, height: number): number => {
    const pixels = width * height;
    if (pixels >= 3840 * 2160) return 20_000_000; // 4K -> 20 Mbps
    if (pixels >= 2560 * 1440) return 10_000_000; // 2K -> 10 Mbps
    if (pixels >= 1920 * 1080) return 5_000_000;  // 1080p -> 5 Mbps
    if (pixels >= 1280 * 720) return 2_500_000;   // 720p -> 2.5 Mbps
    return 1_200_000;                             // 480p/lower -> 1.2 Mbps
  };
  const dynamicBitrate = getDynamicBitrate(vWidth, vHeight);

  // Determine encodable video codec
  const encodableVideoCodec = (await getFirstEncodableVideoCodec(['avc', 'hevc', 'vp9', 'av1'])) || 'avc';

  // Create render canvas
  const canvas = document.createElement('canvas');
  canvas.width = vWidth;
  canvas.height = vHeight;
  const ctx = canvas.getContext('2d', { willReadFrequently: false });
  if (!ctx) {
    throw new Error('Không thể khởi tạo 2D Context cho Canvas render.');
  }

  const canvasSource = new CanvasSource(canvas, {
    codec: encodableVideoCodec,
    bitrate: dynamicBitrate,
    keyFrameInterval: 2,
    hardwareAcceleration: preferSoftware ? 'prefer-software' : 'no-preference',
  });
  output.addVideoTrack(canvasSource);

  let audioSource: AudioBufferSource | null = null;
  if (audioBuffer) {
    const encodableAudioCodec = (await getFirstEncodableAudioCodec(['aac', 'opus'])) || 'aac';
    audioSource = new AudioBufferSource({
      codec: encodableAudioCodec,
      bitrate: 128_000,
    });
    output.addAudioTrack(audioSource);
  }

  await output.start();

  if (audioSource && audioBuffer) {
    await audioSource.add(audioBuffer);
    audioSource.close();
  }

  // Setup CanvasSink to decode source frames
  const canvasSink = new CanvasSink(videoTrack, {
    width: vWidth,
    height: vHeight,
    decoderOptions: {
      hardwareAcceleration: preferSoftware ? 'prefer-software' : 'no-preference',
    },
  });

  let frameIdx = 0;
  for await (const wrapped of canvasSink.canvases()) {
    // 1. Draw base video frame
    ctx.drawImage(wrapped.canvas, 0, 0, vWidth, vHeight);

    // 2. Draw overlays (Subtitles, Blur, Logos, Text)
    drawSubtitleOverlay(
      ctx,
      wrapped.canvas as any,
      vWidth,
      vHeight,
      wrapped.timestamp,
      subtitles,
      styleConfig,
      options.blurOverlays,
      options.logoOverlays,
      options.textOverlays,
      logoBitmaps
    );

    // 3. Add to canvasSource
    await canvasSource.add(wrapped.timestamp, wrapped.duration);

    frameIdx++;
    if (frameIdx % 4 === 0 || frameIdx === totalFrames) {
      const pct = Math.min(99, Math.round((frameIdx / totalFrames) * 100));
      onProgress({
        percentage: pct,
        currentTime: wrapped.timestamp,
        duration,
        status: `Đang xuất video chuẩn studio... (${pct}%)`,
      });
    }
  }

  canvasSource.close();
  await output.finalize();

  const finalMp4Blob = new Blob([target.buffer!], { type: 'video/mp4' });
  return finalMp4Blob;
}

async function preloadLogoOverlays(logoOverlays: LogoOverlay[]): Promise<Record<string, HTMLImageElement>> {
  const logoBitmaps: Record<string, HTMLImageElement> = {};
  await Promise.all(
    logoOverlays.map(async (logo) => {
      try {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.src = logo.url;
        await new Promise((resolve, reject) => {
          img.onload = resolve;
          img.onerror = reject;
        });
        logoBitmaps[logo.id] = img;
        logoBitmaps[logo.url] = img;
      } catch (err) {
        console.warn(`[Preload Logos] Unable to preload logo from ${logo.url}:`, err);
      }
    })
  );
  return logoBitmaps;
}

/**
 * Fallback recorder using standard browser MediaRecorder API (WebM/MP4).
 */
export async function renderWithMediaRecorder(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
    preferredFormat?: 'mp4' | 'webm';
  } = {}
): Promise<Blob> {
  return new Promise(async (resolve, reject) => {
    const video = document.createElement('video');
    if (videoUrl && !videoUrl.startsWith('blob:')) {
      video.crossOrigin = 'anonymous';
    }
    video.src = videoUrl;
    video.muted = true; // Mute video element to guarantee video.play() never gets blocked by autoplay policy

    // Preload and ensure all fonts (Google Fonts & custom uploaded fonts) are ready
    try {
      await loadAllSavedCustomFonts();
      if (typeof document !== 'undefined' && document.fonts) {
        await document.fonts.ready;
      }
    } catch (_fontErr) {}

    // Preload logo images for MediaRecorder canvas overlay
    const logoBitmaps = options.logoOverlays ? await preloadLogoOverlays(options.logoOverlays) : {};

    video.onloadedmetadata = async () => {
      try {
        const vWidth = video.videoWidth || 1280;
        const vHeight = video.videoHeight || 720;
        const duration = video.duration || 10;

        const canvas = document.createElement('canvas');
        canvas.width = vWidth;
        canvas.height = vHeight;
        const ctx = canvas.getContext('2d');

        if (!ctx) {
          reject(new Error('Không thể khởi tạo Canvas 2D'));
          return;
        }

        // Fetch original audio track and decode it
        let originalAudioBuffer: AudioBuffer | null = null;
        try {
          const res = await fetch(videoUrl);
          if (res.ok) {
            const arrBuf = await res.arrayBuffer();
            const actx = new (window.AudioContext || (window as any).webkitAudioContext)();
            originalAudioBuffer = await actx.decodeAudioData(arrBuf);
            await actx.close();
          }
        } catch (e) {
          console.warn('[MediaRecorder Fallback] Không có hoặc không nạp được audio track gốc:', e);
        }

        // Synthesize and mix voiceover audio track if requested
        const videoVolume = options.videoVolume ?? 1.0;
        let audioBuffer: AudioBuffer | null = null;
        if (options.includeVoiceover) {
          try {
            const result = await generateVoiceoverAudioBuffer(
              subtitles,
              duration,
              options.ttsSpeed || 1.0,
              options.ttsPitch || 0
            );
            const ttsAudioBuffer = result.buffer;
            audioBuffer = await mixAudioBuffers(originalAudioBuffer, ttsAudioBuffer, duration, videoVolume);
          } catch (e) {
            console.warn('[MediaRecorder Fallback] Không thể dựng audio thuyết minh, sẽ dùng audio gốc:', e);
            audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
          }
        } else {
          audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
        }

        const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
        const audioCtx = new AudioCtx();
        const dest = audioCtx.createMediaStreamDestination();

        // Ensure the AudioContext is running (important inside sandboxed iframes)
        if (audioCtx.state === 'suspended') {
          await audioCtx.resume();
        }

        let audioSourceNode: AudioBufferSourceNode | null = null;
        if (audioBuffer) {
          audioSourceNode = audioCtx.createBufferSource();
          audioSourceNode.buffer = audioBuffer;
          audioSourceNode.connect(dest);
        }

        const canvasStream = canvas.captureStream(30);
        const combinedTracks = [...canvasStream.getVideoTracks()];
        if (audioBuffer) {
          combinedTracks.push(...dest.stream.getAudioTracks());
        }
        const combinedStream = new MediaStream(combinedTracks);

        let mimeType = '';
        const prefFormat = options.preferredFormat || 'mp4';

        if (prefFormat === 'mp4') {
          if (MediaRecorder.isTypeSupported('video/mp4;codecs=h264,aac')) {
            mimeType = 'video/mp4;codecs=h264,aac';
          } else if (MediaRecorder.isTypeSupported('video/mp4')) {
            mimeType = 'video/mp4';
          }
        }

        if (!mimeType) {
          if (MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')) {
            mimeType = 'video/webm;codecs=vp9,opus';
          } else if (MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')) {
            mimeType = 'video/webm;codecs=vp8,opus';
          } else if (MediaRecorder.isTypeSupported('video/webm')) {
            mimeType = 'video/webm';
          } else if (MediaRecorder.isTypeSupported('video/mp4;codecs=h264,aac')) {
            mimeType = 'video/mp4;codecs=h264,aac';
          } else if (MediaRecorder.isTypeSupported('video/mp4')) {
            mimeType = 'video/mp4';
          }
        }

        const recorderOptions = mimeType ? { mimeType } : undefined;
        const recorder = new MediaRecorder(combinedStream, recorderOptions);
        const chunks: Blob[] = [];

        recorder.ondataavailable = (e) => {
          if (e.data && e.data.size > 0) {
            chunks.push(e.data);
          }
        };

        recorder.onstop = async () => {
          if (audioSourceNode) {
            try { audioSourceNode.stop(); } catch {}
          }
          const finalType = mimeType || 'video/webm';
          const rawBlob = new Blob(chunks, { type: finalType });
          const durationMs = Math.max(1000, Math.round(duration * 1000));
          const durationSec = duration;

          if (finalType.includes('webm')) {
            try {
              fixWebmDuration(rawBlob, durationMs, (fixedBlob) => {
                resolve(fixedBlob);
              });
              return;
            } catch (fixErr) {
              console.warn('[MediaRecorder] Failed to fix webm duration header:', fixErr);
            }
          } else if (finalType.includes('mp4')) {
            try {
              const fixedBlob = await fixMp4Duration(rawBlob, durationSec);
              resolve(fixedBlob);
              return;
            } catch (fixErr) {
              console.warn('[MediaRecorder] Failed to fix mp4 duration header:', fixErr);
            }
          }
          resolve(rawBlob);
        };

        recorder.onerror = (err) => {
          reject(err);
        };

        const renderFrame = () => {
          const curTime = video.currentTime;
          const pct = Math.min(100, Math.round((curTime / duration) * 100));

          onProgress({
            percentage: pct,
            currentTime: curTime,
            duration,
            status: `Đang render video... (${pct}%)`,
          });

          drawSubtitleOverlay(
            ctx,
            video,
            vWidth,
            vHeight,
            curTime,
            subtitles,
            styleConfig,
            options.blurOverlays,
            options.logoOverlays,
            options.textOverlays,
            logoBitmaps
          );

          if (!video.ended && video.currentTime < duration) {
            requestAnimationFrame(renderFrame);
          } else {
            setTimeout(() => {
              if (recorder.state === 'recording') {
                recorder.stop();
              }
            }, 300);
          }
        };

        recorder.start(1000); // Pass timeslice to record chunks progressively and prevent Infinity duration issues
        
        video.play().then(() => {
          if (audioSourceNode) {
            audioSourceNode.start(0);
          }
          renderFrame();
        }).catch((playErr) => {
          console.error('[MediaRecorder Fallback] video.play() failed:', playErr);
          reject(new Error(`Không thể phát video để ghi hình: ${playErr.message}`));
        });

        video.onended = () => {
          setTimeout(() => {
            if (recorder.state === 'recording') {
              recorder.stop();
            }
          }, 300);
        };
      } catch (err) {
        reject(err);
      }
    };

    video.onerror = () => {
      reject(new Error('Không thể tải video nguồn để render.'));
    };
  });
}

/**
 * Main export video entry point. Uses mp4-muxer for MP4 format when supported,
 * with graceful fallback to MediaRecorder.
 */
export async function renderVideoWithSubtitles(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  preferredFormat: 'mp4' | 'webm' | 'mediarecorder' = 'mp4',
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
  } = {}
): Promise<{ blob: Blob; formatUsed: 'mp4' | 'webm' }> {
  if (preferredFormat === 'mp4' && typeof VideoEncoder !== 'undefined') {
    try {
      const blob = await renderWithMp4Muxer(videoUrl, subtitles, styleConfig, onProgress, options, false);
      return { blob, formatUsed: 'mp4' };
    } catch (err: any) {
      console.warn('[Mediabunny] GPU/HW rendering failed, retrying with Software Encoder (prefer-software)...', err);
      onProgress({
        percentage: 0,
        currentTime: 0,
        duration: 1,
        status: 'GPU encoder gián đoạn, đang tự động thử lại bằng Software Encoder (CPU)...',
      });
      try {
        const blob = await renderWithMp4Muxer(videoUrl, subtitles, styleConfig, onProgress, options, true);
        return { blob, formatUsed: 'mp4' };
      } catch (retryErr: any) {
        console.warn('[Mediabunny] Software rendering failed too, falling back to MediaRecorder:', retryErr);
        onProgress({
          percentage: 0,
          currentTime: 0,
          duration: 1,
          status: 'Chuyển sang MediaRecorder fallback...',
        });
      }
    }
  }

  const blob = await renderWithMediaRecorder(videoUrl, subtitles, styleConfig, onProgress, {
    ...options,
    preferredFormat: preferredFormat === 'webm' ? 'webm' : 'mp4',
  });
  const formatUsed = blob.type.includes('mp4') ? 'mp4' : 'webm';
  return { blob, formatUsed };
}
